#! /bin/bash

BASEDIR=$(cd `dirname $0` && pwd)
antlr4="java -Xmx500M -cp ${BASEDIR}/antlr-4.8-complete.jar:$CLASSPATH org.antlr.v4.Tool"
echo $BASEDIR
$antlr4 -Dlanguage=Python3 ${BASEDIR}/../src/sketchon/cql_parser/cqlLexer.g4
$antlr4 -Dlanguage=Python3 ${BASEDIR}/../src/sketchon/cql_parser/cqlParser.g4 -visitor
